
CFLAGS += -O3 -fPIC -ftree-vectorize

#CFLAGS := -Wall -g -fPIC 

CXXFLAGS  += $(CFLAGS)

LDFLAGS	  += -shared -Wl,-Bsymbolic -Wl,--version-script=segmentino/vamp-plugin.map

PLUGIN_EXT   := .so

include Makefile.inc

