
TOOLPREFIX     ?= i586-mingw32msvc-
CXX		= $(TOOLPREFIX)g++
CC		= $(TOOLPREFIX)gcc
LD		= $(TOOLPREFIX)g++
AR		= $(TOOLPREFIX)ar
RANLIB		= $(TOOLPREFIX)ranlib

CFLAGS    += -Wall -O2
CXXFLAGS  += $(CFLAGS) -Iboost_1_53_0
LDFLAGS	  += -shared -static -Wl,-Bsymbolic -static-libgcc -Wl,--retain-symbols-file=segmentino/vamp-plugin.list -fno-exceptions $(shell $(CXX) -print-file-name=libstdc++.a)

PLUGIN_EXT   := .dll

include Makefile.inc

