
CFLAGS := -O3 -ftree-vectorize -mmacosx-version-min=10.7 -arch i386 -arch x86_64 -Ivamp-plugin-sdk -Iqm-dsp -I/usr/local/boost
CXXFLAGS  := $(CFLAGS)

LDFLAGS	  := -mmacosx-version-min=10.7 -arch i386 -arch x86_64 -dynamiclib -exported_symbols_list segmentino/vamp-plugin.list

PLUGIN_EXT   := .dylib

include Makefile.inc

