
CXX	:= i486-mingw32-g++
CC	:= i486-mingw32-gcc

CFLAGS    := -Wall -O2
CXXFLAGS  := $(CFLAGS) -Iboost_1_53_0
LDFLAGS	  := -shared -Wl,-Bsymbolic -static-libgcc -Wl,--version-script=segmentino/vamp-plugin.map -fno-exceptions $(shell $(CXX) -print-file-name=libstdc++.a)

PLUGIN_EXT   := .dll

include Makefile.inc

