
CFLAGS := -O3 -fPIC -ftree-vectorize -I../armadillo-2.4.4/include -I../../vamp-plugin-sdk -I../../qm-dsp

CXXFLAGS  := $(CFLAGS)

LDFLAGS	  := -shared -Wl,-Bstatic -L../../qm-dsp -lqm-dsp -lvamp-sdk -Wl,-Bdynamic 

PLUGIN_EXT   := .so

include build/general/Makefile.inc

